export default function Alerts() {
    return (
        <div className="p-6">
            <h1 className="text-3xl font-bold text-red-600">
                Live AI Alerts
            </h1>

            <p className="mt-2 text-gray-600">
                Real-time alerts generated by LandGuard AI.
            </p>
        </div>
    );
}